module.exports.redirects = [
	{ from: '/casino/sloto-top', to: '/' },
	{ from: '/casino/pm-casino', to: '/casino/parimatch' },
	{ from: '/zapret-na-popolnenie-igornyh-sajtov', to: '' },
	{ from: '/vendors/zeus', to: '/vendor/zeus-play' },
	{ from: '/vendors/yoyougaming', to: '/vendor/yoyougaming' },
	{ from: '/vendors/yggdrasil-gaming', to: '/vendor/yggdrasil-gaming' },
	{ from: '/vendors/xpg', to: '/vendor/xpg' },
	{ from: '/vendors/woohoo', to: '/vendor/woohoo' },
	{ from: '/vendors/wms-gaming', to: '/vendor/wms-gaming' },
	{ from: '/vendors/wgs-technology', to: '/vendor/wgs-technology' },
	{ from: '/vendors/vivogaming', to: '/vendor/vivogaming' },
	{ from: '/vendors/unicum', to: '/vendor/unicum' },
	{ from: '/vendors/triple-cherry', to: '/vendor/triple-cherry' },
	{ from: '/vendors/tom-horn-gaming', to: '/vendor/tom-horn-gaming' },
	{ from: '/vendors/thunderkick', to: '/vendor/thunderkick' },
	{ from: '/vendors/stakelogic', to: '/vendor/stakelogic' },
	{ from: '/vendors/spinomenal', to: '/vendor/spinomenal' },
	{ from: '/vendors/spigo', to: '/vendor/spigo' },
	{ from: '/vendors/skywind-group', to: '/vendor/skywind-group' },
	{ from: '/vendors/skillonnet', to: '/vendor/skillonnet' },
	{ from: '/vendors/sigma-gaming', to: '/vendor/sigma-gaming' },
	{ from: '/vendors/sheriff-gaming', to: '/vendor/sheriff-gaming' },
	{ from: '/vendors/sgs-universal', to: '/vendor/sgs-universal' },
	{ from: '/vendors/sg-gaming', to: '/vendor/sg-gaming' },
	{ from: '/vendors/saucify', to: '/vendor/saucify' },
	{ from: '/vendors/salsa-technology', to: '/vendor/salsa-technology' },
	{ from: '/vendors/sa-gaming', to: '/vendor/sa-gaming' },
	{ from: '/vendors/river-slot', to: '/vendor/river-slot' },
	{ from: '/vendors/relax-gaming', to: '/vendor/relax-gaming' },
	{ from: '/vendors/reflex-gaming', to: '/vendor/reflex-gaming' },
	{ from: '/vendors/reelnrg', to: '/vendor/reelnrg' },
	{ from: '/vendors/red-rake', to: '/vendor/red-rake' },
	{ from: '/vendors/realtime-gaming', to: '/vendor/realtime-gaming' },
	{ from: '/vendors/realistic-games', to: '/vendor/realistic-games' },
	{ from: '/vendors/rabcat-gambling', to: '/vendor/rabcat-gambling' },
	{ from: '/vendors/quickspin', to: '/vendor/quickspin' },
	{ from: '/vendors/push-gaming', to: '/vendor/push-gaming' },
	{ from: '/vendors/probability', to: '/vendor/probability' },
	{ from: '/vendors/pragmatic-play', to: '/vendor/pragmatic-play' },
	{ from: '/vendors/playtech', to: '/vendor/playtech' },
	{ from: '/vendors/playson', to: '/vendor/playson' },
	{ from: '/vendors/play-ngo', to: '/vendor/play-ngo' },
	{ from: '/vendors/platipus-ltd', to: '/vendor/platipus-ltd' },
	{ from: '/vendors/pearfiction-studios', to: '/vendor/pearfiction-studios' },
	{ from: '/vendors/parlay-game', to: '/vendor/parlay-game' },
	{ from: '/vendors/pariplay', to: '/vendor/pariplay' },
	{ from: '/vendors/oryx-gaming', to: '/vendor/oryx-gaming' },
	{ from: '/vendors/ortiz', to: '/vendor/ortiz' },
	{ from: '/vendors/open-bet', to: '/vendor/open-bet' },
	{ from: '/vendors/omi-gaming', to: '/vendor/omi-gaming' },
	{ from: '/vendors/old-skool-studios', to: '/vendor/old-skool-studios' },
	{ from: '/vendors/odobo-limited', to: '/vendor/odobo-limited' },
	{ from: '/vendors/nyx-gaming-group', to: '/vendor/nyx-gaming-group' },
	{ from: '/vendors/novomatic', to: '/vendor/novomatic' },
	{ from: '/vendors/nolimit-city', to: '/vendor/nolimit-city' },
	{ from: '/vendors/noble-gaming', to: '/vendor/noble-gaming' },
	{ from: '/vendors/nextgen-gaming', to: '/vendor/nextgen-gaming' },
	{ from: '/vendors/netoplay', to: '/vendor/netoplay' },
	{ from: '/vendors/netent', to: '/vendor/netent' },
	{ from: '/vendors/nektan', to: '/vendor/nektan' },
	{ from: '/vendors/multislot', to: '/vendor/multislot' },
	{ from: '/vendors/mrslotty', to: '/vendor/mrslotty' },
	{ from: '/vendors/microgaming', to: '/vendor/microgaming' },
	{ from: '/vendors/merkur', to: '/vendor/merkur' },
	{ from: '/vendors/mazooma', to: '/vendor/mazooma' },
	{ from: '/vendors/mascot', to: '/vendor/mascot' },
	{ from: '/vendors/mancala', to: '/vendor/mancala' },
	{ from: '/vendors/magma', to: '/vendor/magma' },
	{ from: '/vendors/lucky-streak', to: '/vendor/lucky-streak' },
	{ from: '/vendors/lightning-box-games', to: '/vendor/lightning-box-games' },
	{ from: '/vendors/leap-gaming', to: '/vendor/leap-gaming' },
	{ from: '/vendors/leander-games', to: '/vendor/leander-games' },
	{ from: '/vendors/kalamba-games', to: '/vendor/kalamba-games' },
	{ from: '/vendors/ka-gaming', to: '/vendor/ka-gaming' },
	{ from: '/vendors/just-for-the-win', to: '/vendor/just-for-the-win' },
	{ from: '/vendors/jdb', to: '/vendor/jdb' },
	{ from: '/vendors/isoftbet', to: '/vendor/isoftbet' },
	{ from: '/vendors/iron-dog-studio', to: '/vendor/iron-dog-studio' },
	{ from: '/vendors/inbet', to: '/vendor/inbet' },
	{ from: '/vendors/igt-cryptologic', to: '/vendor/igt-cryptologic' },
	{ from: '/vendors/igrosoft', to: '/vendor/igrosoft' },
	{ from: '/vendors/iconic-gaming', to: '/vendor/iconic-gaming' },
	{ from: '/vendors/high-5-games', to: '/vendor/high-5-games' },
	{ from: '/vendors/habanero', to: '/vendor/habanero' },
	{ from: '/vendors/gtech-gaming', to: '/vendor/gtech-gaming' },
	{ from: '/vendors/golden-race', to: '/vendor/golden-race' },
	{ from: '/vendors/globotech', to: '/vendor/globotech' },
	{ from: '/vendors/global-game-service', to: '/vendor/global-game-service' },
	{ from: '/vendors/genii', to: '/vendor/genii' },
	{ from: '/vendors/genesis-gaming', to: '/vendor/genesis-gaming' },
	{ from: '/vendors/ganapati', to: '/vendor/ganapati' },
	{ from: '/vendors/gamzix', to: '/vendor/gamzix' },
	{ from: '/vendors/gaming1', to: '/vendor/gaming1' },
	{ from: '/vendors/gamevy', to: '/vendor/gamevy' },
	{ from: '/vendors/gamesys-n-v', to: '/vendor/gamesys-n-v' },
	{ from: '/vendors/gamesos', to: '/vendor/gamesos' },
	{ from: '/vendors/gamefish-global', to: '/vendor/gamefish-global' },
	{ from: '/vendors/gameart', to: '/vendor/gameart' },
	{ from: '/vendors/game360', to: '/vendor/game360' },
	{ from: '/vendors/gamatron', to: '/vendor/gamatron' },
	{ from: '/vendors/fuga-gaming', to: '/vendor/fuga-gaming' },
	{ from: '/vendors/foxium', to: '/vendor/foxium' },
	{ from: '/vendors/felt-gaming', to: '/vendor/felt-gaming' },
	{ from: '/vendors/felix-gaming', to: '/vendor/felix-gaming' },
	{ from: '/vendors/fazi', to: '/vendor/fazi' },
	{ from: '/vendors/fantasma-games', to: '/vendor/fantasma-games' },
	{ from: '/vendors/ezugi', to: '/vendor/ezugi' },
	{ from: '/vendors/evolution-gaming', to: '/vendor/evolution-gaming' },
	{ from: '/vendors/ensis', to: '/vendor/ensis' },
	{ from: '/vendors/endorphina', to: '/vendor/endorphina' },
	{ from: '/vendors/endemol-games', to: '/vendor/endemol-games' },
	{ from: '/vendors/elk-studios', to: '/vendor/elk-studios' },
	{ from: '/vendors/egt', to: '/vendor/egt' },
	{ from: '/vendors/dwg', to: '/vendor/dwg' },
	{ from: '/vendors/dragoon-soft', to: '/vendor/dragoon-soft' },
	{ from: '/vendors/dragonfish', to: '/vendor/dragonfish' },
	{ from: '/vendors/ct-gaming', to: '/vendor/ct-gaming' },
	{ from: '/vendors/cryptologic', to: '/vendor/cryptologic' },
	{ from: '/vendors/core-gaming', to: '/vendor/core-gaming' },
	{ from: '/vendors/concept-gaming', to: '/vendor/concept-gaming' },
	{ from: '/vendors/chartwell', to: '/vendor/chartwell' },
	{ from: '/vendors/cayetano-gaming', to: '/vendor/cayetano-gaming' },
	{ from: '/vendors/casino-technology', to: '/vendor/casino-technology' },
	{ from: '/vendors/bwin-party', to: '/vendor/bwin-party' },
	{ from: '/vendors/bunfox', to: '/vendor/bunfox' },
	{ from: '/vendors/booongo', to: '/vendor/booongo' },
	{ from: '/vendors/booming-games', to: '/vendor/booming-games' },
	{ from: '/vendors/blueprint-gaming', to: '/vendor/blueprint-gaming' },
	{ from: '/vendors/bla-bla-bla-studios', to: '/vendor/bla-bla-bla-studios' },
	{ from: '/vendors/big-time-gaming', to: '/vendor/big-time-gaming' },
	{ from: '/vendors/bgaming', to: '/vendor/bgaming' },
	{ from: '/vendors/bf-games', to: '/vendor/bf-games' },
	{ from: '/vendors/betsoft', to: '/vendor/betsoft' },
	{ from: '/vendors/betixon', to: '/vendor/betixon' },
	{ from: '/vendors/betgames', to: '/vendor/betgames' },
	{ from: '/vendors/betdigital', to: '/vendor/betdigital' },
	{ from: '/vendors/betconstruct', to: '/vendor/betconstruct' },
	{ from: '/vendors/bbin', to: '/vendor/bbin' },
	{ from: '/vendors/barcrest-games', to: '/vendor/barcrest-games' },
	{ from: '/vendors/bang-bang-games', to: '/vendor/bang-bang-games' },
	{ from: '/vendors/bally-technologies', to: '/vendor/bally-technologies' },
	{ from: '/vendors/authentic-gaming', to: '/vendor/authentic-gaming' },
	{
		from: '/vendors/aurum-signature-studios',
		to: '/vendor/aurum-signature-studios'
	},
	{ from: '/vendors/august', to: '/vendor/august' },
	{ from: '/vendors/atmosfera', to: '/vendor/atmosfera' },
	{ from: '/vendors/aspect-games', to: '/vendor/aspect-games' },
	{ from: '/vendors/ash-gaming', to: '/vendor/ash-gaming' },
	{ from: '/vendors/aristocrat', to: '/vendor/aristocrat' },
	{ from: '/vendors/apollo-games', to: '/vendor/apollo-games' },
	{ from: '/vendors/amaya', to: '/vendor/amaya' },
	{ from: '/vendors/amatic-industries', to: '/vendor/amatic-industries' },
	{ from: '/vendors/allwayspin', to: '/vendor/allwayspin' },
	{ from: '/vendors/all41-studios', to: '/vendor/all41-studios' },
	{ from: '/vendors/alfaplay', to: '/vendor/alfaplay' },
	{ from: '/vendors/ainsworth', to: '/vendor/ainsworth' },
	{ from: '/vendors/abzorba-games', to: '/vendor/abzorba-games' },
	{ from: '/vendors/absolute', to: '/vendor/absolute' },
	{ from: '/vendors/888', to: '/vendor/888' },
	{ from: '/vendors/7-mojos', to: '/vendor/7-mojos' },
	{ from: '/vendors/4theplayer', to: '/vendor/4theplayer' },
	{ from: '/vendors/2-by-2-gaming', to: '/vendor/2-by-2-gaming' },
	{ from: '/vendors/1x2-gaming', to: '/vendor/1x2-gaming' },
	{ from: '/vendors/1spin4win', to: '/vendor/1spin4win' },
	{ from: '/vendors/realtime-gaming', to: '/vendor/realtime-gaming' },
	{
		from: '/filter/vse-proizvoditeli-s-softom-na-ispanskom',
		to: '/lang/ispanskiy'
	},
	{
		from: '/filter/vse-proizvoditeli-s-softom-na-angliyskom',
		to: '/lang/angliyskiy'
	},
	{
		from: '/filter/vse-platformy-velikobritanii',
		to: '/country/velikobritaniya'
	},
	{ from: '/filter/vse-platformy-tayvanya', to: '/country/tayvan' },
	{ from: '/filter/vse-platformy-ssha', to: '/country/ssha' },
	{ from: '/filter/vse-platformy-slovenii', to: '/country/sloveniya' },
	{ from: '/filter/vse-platformy-shvetsii', to: '/country/shvetsiya' },
	{ from: '/filter/vse-platformy-rossii', to: '/country/rossiya' },
	{ from: '/filter/vse-platformy-niderlandov', to: '/country/niderlandy' },
	{ from: '/filter/vse-platformy-malty', to: '/country/malta' },
	{ from: '/filter/vse-platformy-latvii', to: '/country/latviya' },
	{ from: '/filter/vse-platformy-kipra', to: '/country/kipr' },
	{ from: '/filter/vse-platformy-kanady', to: '/country/kanada' },
	{ from: '/filter/vse-platformy-izrailya', to: '/country/izrail' },
	{ from: '/filter/vse-platformy-italii', to: '/country/italiya' },
	{ from: '/filter/vse-platformy-ispanii', to: '/country/ispaniya' },
	{ from: '/filter/vse-platformy-estonii', to: '/country/estoniya' },
	{ from: '/filter/vse-platformy-chehii', to: '/country/chehiya' },
	{ from: '/filter/vse-platformy-bolgarii', to: '/country/bolgariya' },
	{ from: '/filter/vse-platformy-avstrii', to: '/country/avstriya' },
	{ from: '/filter/vse-platformy-avstralii', to: '/country/avstraliya' },
	{ from: '/filter/vse-platformy-argentiny', to: '/country/argentina' },
	{ from: '/filter/vse-kazino-s-yandeks-dengi', to: '/payment/yandeksdengi' },
	{ from: '/filter/vse-kazino-s-wirecard', to: '/payment/wirecard' },
	{ from: '/filter/vse-kazino-s-wire-transfer', to: '/payment/wire-transfer' },
	{ from: '/filter/vse-kazino-s-western-union', to: '/payment/western-union' },
	{ from: '/filter/vse-kazino-s-webmoney', to: '/payment/webmoney' },
	{ from: '/filter/vse-kazino-s-wallet-one', to: '/payment/wallet-one' },
	{ from: '/filter/vse-kazino-s-vodafon', to: '/payment/vodafon' },
	{ from: '/filter/vse-kazino-s-visa', to: '/payment/visa' },
	{ from: '/filter/vse-kazino-s-ukash', to: '/payment/ukash' },
	{ from: '/filter/vse-kazino-s-trustpay', to: '/payment/trustpay' },
	{ from: '/filter/vse-kazino-s-trustly', to: '/payment/trustly' },
	{ from: '/filter/vse-kazino-s-tether', to: '/payment/tether' },
	{ from: '/filter/vse-kazino-s-telepay', to: '/payment/telepay' },
	{ from: '/filter/vse-kazino-s-tele2', to: '/payment/tele2' },
	{ from: '/filter/vse-kazino-s-switch', to: '/payment/switch' },
	{ from: '/filter/vse-kazino-s-sticpay', to: '/payment/sticpay' },
	{ from: '/filter/vse-kazino-s-stellar', to: '/payment/stellar' },
	{ from: '/filter/vse-kazino-s-speedcard', to: '/payment/speedcard' },
	{
		from: '/filter/vse-kazino-s-sofort-banking',
		to: '/payment/sofort-banking'
	},
	{ from: '/filter/vse-kazino-s-skrill', to: '/payment/skrill-moneybookers' },
	{
		from: '/filter/vse-kazino-s-sistemoy-sberbank-onlayn',
		to: '/payment/sberbank-onlayn'
	},
	{
		from: '/filter/vse-kazino-s-sistemoy-promsvyaz',
		to: '/payment/promsvyazbank'
	},
	{ from: '/filter/vse-kazino-s-sistemoy-moneta-ru', to: '/payment/monetaru' },
	{
		from: '/filter/vse-kazino-s-sistemoy-dengi-mail-ru',
		to: '/payment/dengi-mailru'
	},
	{ from: '/filter/vse-kazino-s-runpay', to: '/payment/runpay' },
	{ from: '/filter/vse-kazino-s-quickpay', to: '/payment/quickpay' },
	{ from: '/filter/vse-kazino-s-pugglepay', to: '/payment/pugglepay' },
	{
		from: '/filter/vse-kazino-s-privetstvennym-bonusom',
		to: '/type-bonus/privetstvennyy-bonus'
	},
	{ from: '/filter/vse-kazino-s-privat-24', to: '/payment/privat-24' },
	{ from: '/filter/vse-kazino-s-polipayments', to: '/payment/poli' },
	{ from: '/filter/vse-kazino-s-piastrix', to: '/payment/piastrix' },
	{ from: '/filter/vse-kazino-s-perfect-money', to: '/payment/perfect-money' },
	{ from: '/filter/vse-kazino-s-payu', to: '/payment/payu' },
	{ from: '/filter/vse-kazino-s-paysafecard', to: '/payment/paysafecard' },
	{ from: '/filter/vse-kazino-s-paypal', to: '/payment/paypal' },
	{ from: '/filter/vse-kazino-s-payeer', to: '/payment/payeer' },
	{
		from: '/filter/vse-kazino-s-paketami-bonusov',
		to: '/type-bonus/paket-bonusov'
	},
	{
		from: '/filter/vse-kazino-s-oplatoy-cherez-sms-soobscheniya',
		to: '/payment/oplata-cherez-sms-soobshcheniya'
	},
	{ from: '/filter/vse-kazino-s-okpay', to: '/payment/okpay' },
	{ from: '/filter/vse-kazino-s-neteller', to: '/payment/neteller' },
	{ from: '/filter/vse-kazino-s-neosurf', to: '/payment/neosurf' },
	{ from: '/filter/vse-kazino-s-muchbetter', to: '/payment/muchbetter' },
	{ from: '/filter/vse-kazino-s-monobank', to: '/payment/monobank' },
	{ from: '/filter/vse-kazino-s-moneymail', to: '/payment/moneymail' },
	{ from: '/filter/vse-kazino-s-monetix', to: '/payment/monetix' },
	{ from: '/filter/vse-kazino-s-mobicash', to: '/payment/mobicash' },
	{ from: '/filter/vse-kazino-s-master-card', to: '/payment/master-card' },
	{ from: '/filter/vse-kazino-s-maestro', to: '/payment/maestro' },
	{ from: '/filter/vse-kazino-s-litsenziey-ukrainy', to: '/license/ukraina' },
	{
		from: '/filter/vse-kazino-s-litsenziey-kyurasao',
		to: '/license/kyurasao-niderlandskie-antilskie-ostrova'
	},
	{ from: '/filter/vse-kazino-s-litecoin', to: '/payment/litecoin' },
	{ from: '/filter/vse-kazino-s-liqpay', to: '/payment/liqpay' },
	{ from: '/filter/vse-kazino-s-lifecell', to: '/payment/lifecell' },
	{ from: '/filter/vse-kazino-s-kuna', to: '/payment/kuna' },
	{ from: '/filter/vse-kazino-s-ki-vstar', to: '/payment/kievstar' },
	{ from: '/filter/vse-kazino-s-jeton', to: '/payment/jeton' },
	{ from: '/filter/vse-kazino-s-interkassa', to: '/payment/interkassa' },
	{ from: '/filter/vse-kazino-s-interac', to: '/payment/interac' },
	{ from: '/filter/vse-kazino-s-ideal', to: '/payment/ideal' },
	{ from: '/filter/vse-kazino-s-globalmoney', to: '/payment/globalmoney' },
	{ from: '/filter/vse-kazino-s-g-pay', to: '/payment/g-pay' },
	{ from: '/filter/vse-kazino-s-fundsend', to: '/payment/fundsend' },
	{ from: '/filter/vse-kazino-s-express-pay', to: '/payment/express-pay' },
	{ from: '/filter/vse-kazino-s-euteller', to: '/payment/euteller' },
	{ from: '/filter/vse-kazino-s-ethereum', to: '/payment/ethereum' },
	{ from: '/filter/vse-kazino-s-eps', to: '/payment/eps' },
	{ from: '/filter/vse-kazino-s-epay', to: '/payment/epay' },
	{ from: '/filter/vse-kazino-s-entropay', to: '/payment/entropay' },
	{ from: '/filter/vse-kazino-s-ekonto', to: '/payment/ekonto' },
	{ from: '/filter/vse-kazino-s-egopay', to: '/payment/ego-pay' },
	{ from: '/filter/vse-kazino-s-ecopayz', to: '/payment/ecopayz' },
	{ from: '/filter/vse-kazino-s-easypay', to: '/payment/easypay' },
	{ from: '/filter/vse-kazino-s-diners', to: '/payment/diners' },
	{ from: '/filter/vse-kazino-s-dineromail', to: '/payment/dineromail' },
	{ from: '/filter/vse-kazino-s-comgate-agmo', to: '/payment/comgate-agmo' },
	{ from: '/filter/vse-kazino-s-click-and-buy', to: '/payment/click-and-buy' },
	{ from: '/filter/vse-kazino-s-cashu', to: '/payment/cashu' },
	{
		from: '/filter/vse-kazino-s-bonusom-za-depozit',
		to: '/type-bonus/depozitnyy-bonus'
	},
	{
		from: '/filter/vse-kazino-s-bonusom-vip-predlozhenie',
		to: '/type-bonus/vip-predlozheniya'
	},
	{ from: '/filter/vse-kazino-s-bonusom-reload', to: '/type-bonus/reload' },
	{
		from: '/filter/vse-kazino-s-bonusom-na-vtoroy-depozit',
		to: '/type-bonus/bonus-na-vtoroy-depozit'
	},
	{ from: '/filter/vse-kazino-s-bonusom-cashback', to: '/type-bonus/cashback' },
	{
		from: '/filter/vse-kazino-s-bonusnymi-frispinami',
		to: '/type-bonus/frispiny'
	},
	{ from: '/filter/vse-kazino-s-bitcoin', to: '/payment/bitcoin' },
	{
		from: '/filter/vse-kazino-s-bezdepozitnym-bonusom',
		to: '/type-bonus/bezdepozitnyy-bonus'
	},
	{
		from: '/filter/vse-kazino-s-bankovskim-perevodom',
		to: '/payment/bankovskiy-perevod'
	},
	{ from: '/filter/vse-kazino-s-b-pay', to: '/payment/b-pay' },
	{ from: '/filter/vse-kazino-s-astropay', to: '/payment/astropay' },
	{ from: '/filter/vse-kazino-s-apple-pay', to: '/payment/apple-pay' },
	{ from: '/filter/vse-kazino-s-alfapay', to: '/payment/alfapay' },
	{ from: '/vse-kazino-s-alfa-klik', to: '/payment/alfa-klik' },
	{ from: '/filter/filter/vse-kazino-s-advcash', to: '/payment/advcash' },
	{ from: '/filter/vse-kazino-na-rubli', to: '/currency/rubli' },
	{ from: '/filter/vse-kazino-na-kryptu', to: '/currency/kriptovalyuta' },
	{ from: '/filter/vse-kazino-na-grivny', to: '/currency/grivny' },
	{ from: '/filter/vse-kazino-na-funty', to: '/currency/funt-sterlingov' },
	{ from: '/filter/vse-kazino-na-evro', to: '/currency/evro' },
	{ from: '/filter/vse-kazino-na-dollary', to: '/currency/dollary' },
	{ from: '/filter/vse-igry-zeus', to: '/vendor/zeus-play' },
	{ from: '/filter/vse-igry-yoyougaming', to: '/vendor/yoyougaming' },
	{ from: '/filter/vse-igry-yggdrasil-gaming', to: '/vendor/yggdrasil-gaming' },
	{ from: '/filter/vse-igry-xpg', to: '/vendor/xpg' },
	{ from: '/filter/vse-igry-world-match', to: '/vendor/world-match' },
	{ from: '/filter/vse-igry-woohoo', to: '/vendor/woohoo' },
	{ from: '/filter/vse-igry-wms-gaming', to: '/vendor/wms-gaming' },
	{ from: '/filter/vse-igry-wgs-technology', to: '/vendor/wgs-technology' },
	{ from: '/filter/vse-igry-wazdan', to: '/vendor/wazdan' },
	{ from: '/filter/vse-igry-vela-gaming', to: '/vendor/vela-gaming' },
	{ from: '/filter/vse-igry-true-lab', to: '/vendor/true-lab' },
	{
		from: '/filter/vse-igry-triple-edge-studios',
		to: '/vendor/triple-edge-studios'
	},
	{ from: '/filter/vse-igry-triple-cherry', to: '/vendor/triple-cherry' },
	{ from: '/filter/vse-igry-thunderkick', to: '/vendor/thunderkick' },
	{ from: '/filter/vse-igry-stakelogic', to: '/vendor/stakelogic' },
	{ from: '/filter/vse-igry-spribe', to: '/vendor/spribe' },
	{ from: '/filter/vse-igry-spinomenal', to: '/vendor/spinomenal' },
	{ from: '/filter/vse-igry-spigo', to: '/vendor/spigo' },
	{
		from: '/filter/vse-igry-spieldev-game-studio',
		to: '/vendor/spieldev-game-studio'
	},
	{ from: '/filter/vse-igry-spearhead', to: '/vendor/spearhead' },
	{ from: '/filter/vse-igry-spade-gaming', to: '/vendor/spade-gaming' },
	{ from: '/filter/vse-igry-smartsoft', to: '/vendor/smartsoft-games' },
	{ from: '/filter/vse-igry-slotvision', to: '/vendor/slotvision' },
	{ from: '/filter/vse-igry-slotfactory', to: '/vendor/slotfactory' },
	{
		from: '/filter/vse-igry-slingshot-studios',
		to: '/vendor/slingshot-studios'
	},
	{ from: '/filter/vse-igry-skywind-group', to: '/vendor/skywind-group' },
	{ from: '/filter/vse-igry-skillonnet', to: '/vendor/skillonnet' },
	{ from: '/filter/vse-igry-sigma-gaming', to: '/vendor/sigma-gaming' },
	{
		from: '/filter/vse-igry-side-city-studios',
		to: '/vendor/side-city-studios'
	},
	{ from: '/filter/vse-igry-sheriff-gaming', to: '/vendor/sheriff-gaming' },
	{ from: '/filter/vse-igry-sgs-universal', to: '/vendor/sgs-universal' },
	{ from: '/filter/vse-igry-sg-gaming', to: '/vendor/sg-gaming' },
	{ from: '/filter/vse-igry-saucify', to: '/vendor/saucify' },
	{ from: '/filter/vse-igry-salsa-technology', to: '/vendor/salsa-technology' },
	{ from: '/filter/vse-igry-sa-gaming', to: '/vendor/sa-gaming' },
	{ from: '/filter/vse-igry-ruby-play', to: '/vendor/ruby-play' },
	{ from: '/filter/vse-igry-river-slot', to: '/vendor/river-slot' },
	{ from: '/filter/vse-igry-rival', to: '/vendor/rival' },
	{ from: '/filter/vse-igry-relax-gaming', to: '/vendor/relax-gaming' },
	{ from: '/filter/vse-igry-reflex-gaming', to: '/vendor/reflex-gaming' },
	{ from: '/filter/vse-igry-reelplay', to: '/vendor/reelplay' },
	{ from: '/filter/vse-igry-reelnrg', to: '/vendor/reelnrg' },
	{ from: '/filter/vse-igry-red-rake', to: '/vendor/red-rake' },
	{ from: '/filter/vse-igry-realtime-gaming', to: '/vendor/realtime-gaming' },
	{ from: '/filter/vse-igry-realistic-games', to: '/vendor/realistic-games' },
	{ from: '/filter/vse-igry-quickspin', to: '/vendor/quickspin' },
	{ from: '/filter/vse-igry-quickfire', to: '/vendor/quickfire' },
	{ from: '/filter/vse-igry-push-gaming', to: '/vendor/push-gaming' },
	{ from: '/filter/vse-igry-pragmatic-play', to: '/vendor/pragmatic-play' },
	{ from: '/filter/vse-igry-playtech', to: '/vendor/playtech' },
	{ from: '/filter/vse-igry-playson', to: '/vendor/playson' },
	{ from: '/filter/vse-igry-play-ngo', to: '/vendor/playn-go' },
	{ from: '/filter/vse-igry-platipus-ltd', to: '/vendor/platipus-ltd' },
	{ from: '/filter/vse-igry-pg-soft', to: '/vendor/pg-soft' },
	{
		from: '/filter/vse-igry-pearfiction-studios',
		to: '/vendor/pearfiction-studios'
	},
	{ from: '/filter/vse-igry-parlay-games', to: '/vendor/parlay-game' },
	{ from: '/filter/vse-igry-pariplay', to: '/vendor/pariplay' },
	{ from: '/filter/vse-igry-oryx-gaming', to: '/vendor/oryx-gaming' },
	{ from: '/filter/vse-igry-ortiz', to: '/vendor/ortiz' },
	{ from: '/filter/vse-igry-open-bet', to: '/vendor/open-bet' },
	{ from: '/filter/vse-igry-onetouch', to: '/vendor/onetouch' },
	{
		from: '/filter/vse-igry-old-skool-studios',
		to: '/vendor/old-skool-studios'
	},
	{ from: '/filter/vse-igry-odobo-limited', to: '/vendor/odobo-limited' },
	{ from: '/filter/vse-igry-nyx-gaming', to: '/vendor/nyx-gaming-group' },
	{ from: '/filter/vse-igry-novomatic', to: '/vendor/novomatic' },
	{ from: '/filter/vse-igry-nolimit-city', to: '/vendor/nolimit-city' },
	{ from: '/filter/vse-igry-noble-gaming', to: '/vendor/noble-gaming' },
	{ from: '/filter/vse-igry-nextgen-gaming', to: '/vendor/nextgen-gaming' },
	{ from: '/filter/vse-igry-netoplay', to: '/vendor/netoplay' },
	{ from: '/filter/vse-igry-netgame', to: '/vendor/netgame' },
	{ from: '/filter/vse-igry-netent', to: '/vendor/netent' },
	{ from: '/filter/vse-igry-nektan', to: '/vendor/nektan' },
	{ from: '/filter/vse-igry-multislot', to: '/vendor/multislot' },
	{ from: '/filter/vse-igry-mrslotty', to: '/vendor/mrslotty' },
	{ from: '/filter/vse-igry-microgaming', to: '/vendor/microgaming' },
	{ from: '/filter/vse-igry-mga-games', to: '/vendor/mga-games' },
	{ from: '/filter/vse-igry-merkur', to: '/vendor/merkur' },
	{ from: '/filter/vse-igry-mazooma', to: '/vendor/mazooma' },
	{ from: '/filter/vse-igry-mascot', to: '/vendor/mascot' },
	{ from: '/filter/vse-igry-mancala', to: '/vendor/mancala' },
	{ from: '/filter/vse-igry-magma', to: '/vendor/magma' },
	{ from: '/filter/vse-igry-lucky-streak', to: '/vendor/lucky-streak' },
	{
		from: '/filter/vse-igry-lightning-box-games',
		to: '/vendor/lightning-box-games'
	},
	{ from: '/filter/vse-igry-leap-gaming', to: '/vendor/leap-gaming' },
	{ from: '/filter/vse-igry-leander-games', to: '/vendor/leander-games' },
	{ from: '/filter/vse-igry-kalamba-games', to: '/vendor/kalamba-games' },
	{ from: '/filter/vse-igry-ka-gaming', to: '/vendor/ka-gaming' },
	{ from: '/filter/vse-igry-just-for-the-win', to: '/vendor/just-for-the-win' },
	{ from: '/filter/vse-igry-join-games', to: '/vendor/join-games' },
	{ from: '/filter/vse-igry-jdb', to: '/vendor/jdb' },
	{ from: '/filter/vse-igry-isoftbet', to: '/vendor/isoftbet' },
	{ from: '/filter/vse-igry-iron-dog-studio', to: '/vendor/iron-dog-studio' },
	{ from: '/filter/vse-igry-inspired-gaming', to: '/vendor/inspired-gaming' },
	{ from: '/filter/vse-igry-inbet', to: '/vendor/inbet' },
	{ from: '/filter/vse-igry-igt', to: '/vendor/igt' },
	{ from: '/filter/vse-igry-igrosoft', to: '/vendor/igrosoft' },
	{ from: '/filter/vse-igry-iconic-gaming', to: '/vendor/iconic-gaming' },
	{ from: '/filter/vse-igry-high-flyer-games', to: '/vendor/high-flyer-games' },
	{ from: '/filter/vse-igry-high-5-games', to: '/vendor/high-5-games' },
	{ from: '/filter/vse-igry-habanero', to: '/vendor/habanero' },
	{ from: '/filter/vse-igry-gtech-gaming', to: '/vendor/gtech-gaming' },
	{ from: '/filter/vse-igry-golden-race', to: '/vendor/golden-race' },
	{ from: '/filter/vse-igry-globotech', to: '/vendor/globotech' },
	{
		from: '/filter/vse-igry-global-game-service',
		to: '/vendor/global-game-service'
	},
	{ from: '/filter/vse-igry-genii', to: '/vendor/genii' },
	{ from: '/filter/vse-igry-genesis-gaming', to: '/vendor/genesis-gaming' },
	{ from: '/filter/vse-igry-ganapati', to: '/vendor/ganapati' },
	{ from: '/filter/vse-igry-gamzix', to: '/vendor/gamzix' },
	{ from: '/filter/vse-igry-gamshy', to: '/vendor/gamshy' },
	{ from: '/filter/vse-igry-gamomat', to: '/vendor/gamomat' },
	{ from: '/filter/vse-igry-gaming1', to: '/vendor/gaming-1' },
	{ from: '/filter/vse-igry-gamevy', to: '/vendor/gamevy' },
	{ from: '/filter/vse-igry-gamesys-n-v', to: '/vendor/gamesys-nv' },
	{ from: '/filter/vse-igry-gamesos', to: '/vendor/gamesos' },
	{ from: '/filter/vse-igry-gamescale', to: '/vendor/gamescale' },
	{ from: '/filter/vse-igry-games-lab', to: '/vendor/games-lab' },
	{ from: '/filter/vse-igry-gameplay', to: '/vendor/gameplay' },
	{ from: '/filter/vse-igry-gamefish-global', to: '/vendor/gamefish-global' },
	{
		from: '/filter/vse-igry-gameburger-studios',
		to: '/vendor/gameburger-studios'
	},
	{ from: '/filter/vse-igry-game360', to: '/vendor/game360' },
	{ from: '/filter/vse-igry-gamatron', to: '/vendor/gamatron' },
	{ from: '/filter/vse-igry-fugaso', to: '/vendor/fugaso' },
	{ from: '/filter/vse-igry-fuga-gaming', to: '/vendor/fuga-gaming' },
	{ from: '/filter/vse-igry-foxium', to: '/vendor/foxium' },
	{ from: '/filter/vse-igry-felt-gaming', to: '/vendor/felt-gaming' },
	{ from: '/filter/vse-igry-felix-gaming', to: '/vendor/felix-gaming' },
	{ from: '/filter/vse-igry-fazi', to: '/vendor/fazi' },
	{ from: '/filter/vse-igry-fantasma-games', to: '/vendor/fantasma-games' },
	{ from: '/filter/vse-igry-ezugi', to: '/vendor/ezugi' },
	{ from: '/filter/vse-igry-evolution-gaming', to: '/vendor/evolution-gaming' },
	{ from: '/filter/vse-igry-espresso-games', to: '/vendor/espresso-games' },
	{ from: '/filter/vse-igry-ensis', to: '/vendor/ensis' },
	{ from: '/filter/vse-igry-endorphina', to: '/vendor/endorphina' },
	{ from: '/filter/vse-igry-endemol-games', to: '/vendor/endemol-games' },
	{ from: '/filter/vse-igry-elk-studios', to: '/vendor/elk-studios' },
	{ from: '/filter/vse-igry-egt', to: '/vendor/egt' },
	{ from: '/filter/vse-igry-dwg', to: '/vendor/dwg' },
	{ from: '/filter/vse-igry-dragonfish', to: '/vendor/dragonfish' },
	{ from: '/filter/vse-igry-ct-gaming', to: '/vendor/ct-gaming' },
	{ from: '/filter/vse-igry-cryptologic', to: '/vendor/cryptologic' },
	{ from: '/filter/vse-igry-core-gaming', to: '/vendor/core-gaming' },
	{ from: '/filter/vse-igry-chartwell', to: '/vendor/chartwell' },
	{ from: '/filter/vse-igry-cayetano-gaming', to: '/vendor/cayetano-gaming' },
	{
		from: '/filter/vse-igry-casino-technology',
		to: '/vendor/casino-technology'
	},
	{ from: '/filter/vse-igry-bwin-party', to: '/vendor/bwinparty' },
	{ from: '/filter/vse-igry-bunfox', to: '/vendor/bunfox' },
	{ from: '/filter/vse-igry-booongo', to: '/vendor/booongo' },
	{ from: '/filter/vse-igry-booming-games', to: '/vendor/booming-games' },
	{ from: '/filter/vse-igry-blueprint-gaming', to: '/vendor/blueprint-gaming' },
	{
		from: '/filter/vse-igry-bla-bla-bla-studios',
		to: '/vendor/bla-bla-bla-studios'
	},
	{ from: '/filter/vse-igry-big-time-gaming', to: '/vendor/big-time-gaming' },
	{ from: '/filter/vse-igry-bgaming', to: '/vendor/bgaming' },
	{ from: '/filter/vse-igry-bf-games', to: '/vendor/bf-games' },
	{ from: '/filter/vse-igry-betsoft', to: '/vendor/betsoft' },
	{ from: '/filter/vse-igry-betixon', to: '/vendor/betixon' },
	{ from: '/filter/vse-igry-betgames', to: '/vendor/betgames' },
	{ from: '/filter/vse-igry-betdigital', to: '/vendor/betdigital' },
	{ from: '/filter/vse-igry-betconstruct', to: '/vendor/betconstruct' },
	{ from: '/filter/vse-igry-bbin', to: '/vendor/bbin' },
	{ from: '/filter/vse-igry-bang-bang-games', to: '/vendor/bang-bang-games' },
	{
		from: '/filter/vse-igry-bally-technologies',
		to: '/vendor/bally-technologies'
	},
	{ from: '/filter/vse-igry-authentic-gaming', to: '/vendor/authentic-gaming' },
	{ from: '/filter/vse-igry-august', to: '/vendor/august' },
	{ from: '/filter/vse-igry-atmosfera', to: '/vendor/atmosfera' },
	{ from: '/filter/vse-igry-aspect-games', to: '/vendor/aspect-games' },
	{ from: '/filter/vse-igry-ash-gaming', to: '/vendor/ash-gaming' },
	{ from: '/filter/vse-igry-aristocrat', to: '/vendor/aristocrat' },
	{ from: '/filter/vse-igry-apollo-games', to: '/vendor/apollo-games' },
	{ from: '/filter/vse-igry-amaya', to: '/vendor/amaya' },
	{
		from: '/filter/vse-igry-amatic-indastries',
		to: '/vendor/amatic-industries'
	},
	{ from: '/filter/vse-igry-allwayspin', to: '/vendor/allwayspin' },
	{ from: '/filter/vse-igry-alfaplay', to: '/vendor/alfaplay' },
	{ from: '/filter/vse-igry-ainsworth', to: '/vendor/ainsworth' },
	{ from: '/filter/vse-igry-abzorba-games', to: '/vendor/abzorba-games' },
	{ from: '/filter/vse-igry-absolut', to: '/vendor/absolute' },
	{ from: '/filter/vse-igry-888', to: '/vendor/888' },
	{ from: '/filter/vse-igry-7-mojos', to: '/vendor/7-mojos' },
	{ from: '/filter/vse-igry-2-by-2-gaming', to: '/vendor/2-by-2-gaming' },
	{ from: '/filter/vse-igry-1h2-gaming', to: '/vendor/1x2-gaming' },
	{
		from: '/filter/vse-igrovye-avtomaty-rabcat',
		to: '/vendor/rabcat-gambling'
	},
	{ from: '/filter/vse-igrovye-avtomaty-gameart', to: '/vendor/gameart' },
	{ from: '/filter/vse-bonusy-wulkan777', to: '/casino/vulkan777' },
	{ from: '/filter/vse-bonusy-riobet', to: '/casino/riobet' },
	{ from: '/filter/vse-bonusy-kazino-zigzag-777', to: '/casino/zigzag777' },
	{ from: '/filter/vse-bonusy-kazino-zet-casino', to: '/casino/zet-casino' },
	{ from: '/filter/vse-bonusy-kazino-kaboo', to: '/casino/kaboo' },
	{ from: '/filter/vse-bonusy-kazino-joo-casino', to: '/casino/joo' },
	{ from: '/filter/vse-bonusy-kazino-jetbull', to: '/casino/jetbull' },
	{ from: '/filter/vse-bonusy-kazino-ivi-casino', to: '/casino/ivi' },
	{ from: '/filter/vse-bonusy-kazino-ik-vulkan', to: '/casino/ik-vulkan' },
	{ from: '/filter/vse-bonusy-kazino-guts', to: '/casino/guts' },
	{ from: '/filter/vse-bonusy-kazino-gunsbet', to: '/casino/gunsbet' },
	{ from: '/filter/vse-bonusy-kazino-grand-ivy', to: '/casino/grand-ivy' },
	{ from: '/filter/vse-bonusy-kazino-grand-casino', to: '/casino/grand' },
	{
		from: '/filter/vse-bonusy-kazino-good-day-4-play',
		to: '/casino/good-day-4-play'
	},
	{ from: '/filter/vse-bonusy-kazino-gms-deluxe', to: '/casino/gms-deluxe' },
	{ from: '/filter/vse-bonusy-kazino-frank', to: '/casino/frank' },
	{ from: '/filter/vse-bonusy-kazino-eldorado', to: '/casino/eldorado' },
	{ from: '/filter/vse-bonusy-kazino-eldorado-24', to: '/casino/eldorado' },
	{ from: '/filter/vse-bonusy-kazino-dzhekpot', to: '/casino/dzekpot' },
	{ from: '/filter/vse-bonusy-kazino-drift', to: '/casino/drift' },
	{
		from: '/filter/vse-bonusy-kazino-dostupnye-v-tadzhikistane',
		to: '/country/tadzhikistan'
	},
	{
		from: '/filter/vse-bonusy-kazino-dostupnye-v-rumynii',
		to: '/country/rumyniya'
	},
	{ from: '/filter/vse-bonusy-kazino-dostupnye-v-litve', to: '/country/litva' },
	{
		from: '/filter/vse-bonusy-kazino-dostupnye-v-azerbaydzhane',
		to: '/country/azerbaydzhan'
	},
	{ from: '/filter/vse-bonusy-kazino-casinia', to: '/casino/casinia' },
	{ from: '/filter/vse-bonusy-kazino-cashmio', to: '/casino/cashmio' },
	{ from: '/filter/vse-bonusy-kazino-cadoola', to: '/casino/cadoola' },
	{ from: '/filter/vse-bonusy-kazino-boaboa', to: '/casino/boaboa' },
	{ from: '/filter/vse-bonusy-kazino-argo', to: '/casino/argo' },
	{
		from: '/filter/vse-bonusy-kazino-aladdins-gold',
		to: '/casino/aladdins-gold'
	},
	{ from: '/filter/vse-bonusy-kazino-admiral-888', to: '/casino/admiral-888' },
	{ from: '/filter/vse-bonusy-fairplay', to: '/casino/fairplay' },
	{ from: '/filter/vse-bonusy-elslots', to: '/casino/elslots' },
	{ from: '/filter/vse-bonusy-dostupnye-v-vengrii', to: '/country/vengriya' },
	{
		from: '/filter/vse-bonusy-dostupnye-v-uzbekistane',
		to: '/country/uzbekistan'
	},
	{ from: '/filter/vse-bonusy-dostupnye-v-ukraine', to: '/country/ukraina' },
	{ from: '/filter/vse-bonusy-dostupnye-v-slovenii', to: '/country/sloveniya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-slovakii', to: '/country/slovakiya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-rossii', to: '/country/rossiya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-polshe', to: '/country/polsha' },
	{ from: '/filter/vse-bonusy-dostupnye-v-norvegii', to: '/country/norvegiya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-moldavii', to: '/country/moldaviya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-latvii', to: '/country/latviya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-kirgizii', to: '/country/kirgiziya' },
	{
		from: '/filter/vse-bonusy-dostupnye-v-kazahstane',
		to: '/country/kazahstan'
	},
	{ from: '/filter/vse-bonusy-dostupnye-v-izraile', to: '/country/izrail' },
	{ from: '/filter/vse-bonusy-dostupnye-v-gruzii', to: '/country/gruziya' },
	{
		from: '/filter/vse-bonusy-dostupnye-v-finlyandii',
		to: '/country/finlyandiya'
	},
	{ from: '/filter/vse-bonusy-dostupnye-v-estonii', to: '/country/estoniya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-bolgarii', to: '/country/bolgariya' },
	{ from: '/filter/vse-bonusy-dostupnye-v-belorussii', to: '/country/belarus' },
	{ from: '/filter/vse-bonusy-dostupnye-v-armenii', to: '/country/armeniya' },
	{ from: '/filter/vse-bonusy-buran-casino', to: '/casino/buran' },
	{ from: '/filter/vse-bonusy-booi-casino', to: '/casino/booi' },
	{ from: '/filter/vse-bonusy-bitcoinplay-casino', to: '/casino/bitcoinplay' },
	{ from: '/filter/vse-bonusy-big-azart', to: '/casino/big-azart' },
	{ from: '/filter/vse-bonusy-azino-888', to: '/casino/azino-888' },
	{ from: '/filter/vse-bonusy-azino-777', to: '/casino/azino-777' },
	{ from: '/filter/vse-bonusy-azartmania', to: '/casino/azartmania' },
	{ from: '/filter/vse-bonusy-azart-zona', to: '/casino/azart-zona' },
	{ from: '/filter/vse-bonusi-casino-redkings', to: '/casino/redkings' },
	{ from: '/filter/kazino-s-raznymi-bonusami', to: '/bonuses' },
	{ from: '/filter/kazino-s-onlayn-slotami-egt', to: '/vendor/egt' },
	{ from: '/filter/kazino-s-onlayn-igrami-playson', to: '/vendor/playson' },
	{ from: '/filter/kazino-s-igrami-zeus', to: '/vendor/zeus-play' },
	{ from: '/filter/kazino-s-igrami-yoyougaming', to: '/vendor/yoyougaming' },
	{
		from: '/filter/kazino-s-igrami-yggdrasil-gaming',
		to: '/vendor/yggdrasil-gaming'
	},
	{ from: '/filter/kazino-s-igrami-xpg', to: '/vendor/xpg' },
	{ from: '/filter/kazino-s-igrami-world-match', to: '/vendor/world-match' },
	{ from: '/filter/kazino-s-igrami-woohoo', to: '/vendor/woohoo' },
	{ from: '/filter/kazino-s-igrami-wms', to: '/vendor/wms-gaming' },
	{
		from: '/filter/kazino-s-igrami-wgs-technology',
		to: '/vendor/wgs-technology'
	},
	{ from: '/filter/kazino-s-igrami-wazdan', to: '/vendor/wazdan' },
	{ from: '/filter/kazino-s-igrami-vela-gaming', to: '/vendor/vela-gaming' },
	{ from: '/filter/kazino-s-igrami-unicum', to: '/vendor/unicum' },
	{ from: '/filter/kazino-s-igrami-true-lab', to: '/vendor/true-lab' },
	{
		from: '/filter/kazino-s-igrami-triple-edge-studios',
		to: '/vendor/triple-edge-studios'
	},
	{ from: '/filter/kazino-s-igrami-tripe-cherry', to: '/vendor/triple-cherry' },
	{
		from: '/filter/kazino-s-igrami-tom-horn-gaming',
		to: '/vendor/tom-horn-gaming'
	},
	{ from: '/filter/kazino-s-igrami-thunderkick', to: '/vendor/thunderkick' },
	{ from: '/filter/kazino-s-igrami-swintt', to: '/vendor/swintt' },
	{ from: '/filter/kazino-s-igrami-stakelogic', to: '/vendor/stakelogic' },
	{ from: '/filter/kazino-s-igrami-sprible', to: '/vendor/spribe' },
	{ from: '/filter/kazino-s-igrami-spinomenal', to: '/vendor/spinomenal' },
	{ from: '/filter/kazino-s-igrami-spigo', to: '/vendor/spigo' },
	{
		from: '/filter/kazino-s-igrami-spieldev-game-studio',
		to: '/vendor/spieldev-game-studio'
	},
	{ from: '/filter/kazino-s-igrami-spearhead', to: '/vendor/spearhead' },
	{ from: '/filter/kazino-s-igrami-spade-gaming', to: '/vendor/spade-gaming' },
	{ from: '/filter/kazino-s-igrami-smartsoft', to: '/vendor/smartsoft-games' },
	{ from: '/filter/kazino-s-igrami-slotvision', to: '/vendor/slotvision' },
	{ from: '/filter/kazino-s-igrami-slotfactory', to: '/vendor/slotfactory' },
	{
		from: '/filter/kazino-s-igrami-slingoshot-studios',
		to: '/vendor/slingshot-studios'
	},
	{
		from: '/filter/kazino-s-igrami-skywind-group',
		to: '/vendor/skywind-group'
	},
	{ from: '/filter/kazino-s-igrami-skillonnet', to: '/vendor/skillonnet' },
	{ from: '/filter/kazino-s-igrami-sigma-gaming', to: '/vendor/sigma-gaming' },
	{
		from: '/filter/kazino-s-igrami-side-city-studios',
		to: '/vendor/side-city-studios'
	},
	{
		from: '/filter/kazino-s-igrami-sheriff-gaming',
		to: '/vendor/sheriff-gaming'
	},
	{
		from: '/filter/kazino-s-igrami-sgs-universal',
		to: '/vendor/sgs-universal'
	},
	{ from: '/filter/kazino-s-igrami-sg-gaming', to: '/vendor/sg-gaming' },
	{ from: '/filter/kazino-s-igrami-saucify', to: '/vendor/saucify' },
	{
		from: '/filter/kazino-s-igrami-salsa-technology',
		to: '/vendor/salsa-technology'
	},
	{ from: '/filter/kazino-s-igrami-sa-gaming', to: '/vendor/sa-gaming' },
	{ from: '/filter/kazino-s-igrami-rush-gaming', to: '/vendor/sa-gaming' },
	{ from: '/filter/kazino-s-igrami-ruby-play', to: '/vendor/ruby-play' },
	{ from: '/filter/kazino-s-igrami-river-slot', to: '/vendor/river-slot' },
	{ from: '/filter/kazino-s-igrami-rival', to: '/vendor/rival' },
	{ from: '/filter/kazino-s-igrami-relax-gaming', to: '/vendor/relax-gaming' },
	{
		from: '/filter/kazino-s-igrami-reflex-gaming',
		to: '/vendor/reflex-gaming'
	},
	{ from: '/filter/kazino-s-igrami-reelplay', to: '/vendor/reelplay' },
	{ from: '/filter/kazino-s-igrami-reelnrg', to: '/vendor/reelnrg' },
	{
		from: '/filter/kazino-s-igrami-red-tiger-gaming',
		to: '/vendor/red-tiger-gaming'
	},
	{ from: '/filter/kazino-s-igrami-red-rake', to: '/vendor/red-rake' },
	{
		from: '/filter/kazino-s-igrami-realtime-gaming',
		to: '/vendor/realtime-gaming'
	},
	{
		from: '/filter/kazino-s-igrami-realistic-games',
		to: '/vendor/realistic-games'
	},
	{ from: '/filter/kazino-s-igrami-rabcat', to: '/vendor/rabcat-gambling' },
	{ from: '/filter/kazino-s-igrami-quickspin', to: '/vendor/quickspin' },
	{ from: '/filter/kazino-s-igrami-quickfire', to: '/vendor/quickfire' },
	{ from: '/filter/kazino-s-igrami-probability', to: '/vendor/probability' },
	{
		from: '/filter/kazino-s-igrami-pragmatic-play',
		to: '/vendor/pragmatic-play'
	},
	{ from: '/filter/kazino-s-igrami-playtech', to: '/vendor/playtech' },
	{ from: '/filter/kazino-s-igrami-play-n-go', to: '/vendor/playn-go' },
	{ from: '/filter/kazino-s-igrami-platipus-ltd', to: '/vendor/platipus-ltd' },
	{ from: '/filter/kazino-s-igrami-pg-soft', to: '/vendor/pg-soft' },
	{
		from: '/filter/kazino-s-igrami-pearfiction-studios',
		to: '/vendor/pearfiction-studios'
	},
	{ from: '/filter/kazino-s-igrami-parlay-games', to: '/vendor/parlay-game' },
	{ from: '/filter/kazino-s-igrami-pari-play', to: '/vendor/pariplay' },
	{ from: '/filter/kazino-s-igrami-oryx-gaming', to: '/vendor/oryx-gaming' },
	{ from: '/filter/kazino-s-igrami-ortiz', to: '/vendor/ortiz' },
	{ from: '/filter/kazino-s-igrami-open-bet', to: '/vendor/open-bet' },
	{ from: '/filter/kazino-s-igrami-onetouch', to: '/vendor/onetouch' },
	{
		from: '/filter/kazino-s-igrami-old-skool-studios',
		to: '/vendor/old-skool-studios'
	},
	{
		from: '/filter/kazino-s-igrami-odobo-limited',
		to: '/vendor/odobo-limited'
	},
	{
		from: '/filter/kazino-s-igrami-nyx-gaming',
		to: '/vendor/nyx-gaming-group'
	},
	{ from: '/filter/kazino-s-igrami-novomatic', to: '/vendor/novomatic' },
	{ from: '/filter/kazino-s-igrami-nolimit-city', to: '/vendor/nolimit-city' },
	{ from: '/filter/kazino-s-igrami-noble-gaming', to: '/vendor/noble-gaming' },
	{
		from: '/filter/kazino-s-igrami-nextgen-gaming',
		to: '/vendor/nextgen-gaming'
	},
	{ from: '/filter/kazino-s-igrami-netoplay', to: '/vendor/netoplay' },
	{ from: '/filter/kazino-s-igrami-netgame', to: '/vendor/netgame' },
	{ from: '/filter/kazino-s-igrami-netent', to: '/vendor/netent' },
	{ from: '/filter/kazino-s-igrami-nektan', to: '/vendor/nektan' },
	{ from: '/filter/kazino-s-igrami-multislot', to: '/vendor/multislot' },
	{ from: '/filter/kazino-s-igrami-mrslotty', to: '/vendor/mrslotty' },
	{ from: '/filter/kazino-s-igrami-microgaming', to: '/vendor/microgaming' },
	{ from: '/filter/kazino-s-igrami-mga-games', to: '/vendor/mga-games' },
	{ from: '/filter/kazino-s-igrami-merkur', to: '/vendor/merkur' },
	{ from: '/filter/kazino-s-igrami-mazooma', to: '/vendor/mazooma' },
	{ from: '/filter/kazino-s-igrami-mascot', to: '/vendor/mascot' },
	{ from: '/filter/kazino-s-igrami-mancala', to: '/vendor/mancala' },
	{ from: '/filter/kazino-s-igrami-magma', to: '/vendor/magma' },
	{ from: '/filter/kazino-s-igrami-lucky-streak', to: '/vendor/lucky-streak' },
	{
		from: '/filter/kazino-s-igrami-lightning-box-games',
		to: '/vendor/lightning-box-games'
	},
	{ from: '/filter/kazino-s-igrami-leap-gaming', to: '/vendor/leap-gaming' },
	{
		from: '/filter/kazino-s-igrami-leander-games',
		to: '/vendor/leander-games'
	},
	{
		from: '/filter/kazino-s-igrami-kalamba-games',
		to: '/vendor/kalamba-games'
	},
	{ from: '/filter/kazino-s-igrami-ka-gaming', to: '/vendor/ka-gaming' },
	{
		from: '/filter/kazino-s-igrami-just-for-the-win',
		to: '/vendor/just-for-the-win'
	},
	{ from: '/filter/kazino-s-igrami-join-games', to: '/vendor/join-games' },
	{ from: '/filter/kazino-s-igrami-jdb', to: '/vendor/jdb' },
	{ from: '/filter/kazino-s-igrami-isoftbet', to: '/vendor/isoftbet' },
	{
		from: '/filter/kazino-s-igrami-iron-dog-studio',
		to: '/vendor/iron-dog-studio'
	},
	{
		from: '/filter/kazino-s-igrami-inspired-gaming',
		to: '/vendor/inspired-gaming'
	},
	{ from: '/filter/kazino-s-igrami-inbet', to: '/vendor/inbet' },
	{ from: '/filter/kazino-s-igrami-igt', to: '/vendor/igt' },
	{ from: '/filter/kazino-s-igrami-igrosoft', to: '/vendor/igrosoft' },
	{
		from: '/filter/kazino-s-igrami-iconic-gaming',
		to: '/vendor/iconic-gaming'
	},
	{
		from: '/filter/kazino-s-igrami-high-flyer-games',
		to: '/vendor/high-flyer-games'
	},
	{ from: '/filter/kazino-s-igrami-high-5-games', to: '/vendor/high-5-games' },
	{ from: '/filter/kazino-s-igrami-habanero', to: '/vendor/habanero' },
	{ from: '/filter/kazino-s-igrami-gtech-gaming', to: '/vendor/gtech-gaming' },
	{ from: '/filter/kazino-s-igrami-golden-race', to: '/vendor/golden-race' },
	{ from: '/filter/kazino-s-igrami-globotech', to: '/vendor/globotech' },
	{
		from: '/filter/kazino-s-igrami-global-game-service',
		to: '/vendor/global-game-service'
	},
	{ from: '/filter/kazino-s-igrami-genii', to: '/vendor/genii' },
	{
		from: '/filter/kazino-s-igrami-genesis-gaming',
		to: '/vendor/genesis-gaming'
	},
	{ from: '/filter/kazino-s-igrami-ganapati', to: '/vendor/ganapati' },
	{ from: '/filter/kazino-s-igrami-gamzix', to: '/vendor/gamzix' },
	{ from: '/filter/kazino-s-igrami-gamshy', to: '/vendor/gamshy' },
	{ from: '/filter/kazino-s-igrami-gamomat', to: '/vendor/gamomat' },
	{ from: '/filter/kazino-s-igrami-gaming1', to: '/vendor/gaming-1' },
	{ from: '/filter/kazino-s-igrami-gamevy', to: '/vendor/gamevy' },
	{ from: '/filter/kazino-s-igrami-gamesys-n-v', to: '/vendor/gamesys-nv' },
	{ from: '/filter/kazino-s-igrami-gamesos', to: '/vendor/gamesos' },
	{ from: '/filter/kazino-s-igrami-gamescale', to: '/vendor/gamescale' },
	{ from: '/filter/kazino-s-igrami-games-lab', to: '/vendor/games-lab' },
	{ from: '/filter/kazino-s-igrami-gameplay', to: '/vendor/gameplay' },
	{
		from: '/filter/kazino-s-igrami-gamefish-global',
		to: '/vendor/gamefish-global'
	},
	{
		from: '/filter/kazino-s-igrami-gameburger-studios',
		to: '/vendor/gameburger-studios'
	},
	{ from: '/filter/kazino-s-igrami-gameart', to: '/vendor/gameart' },
	{ from: '/filter/kazino-s-igrami-game360', to: '/vendor/game360' },
	{ from: '/filter/kazino-s-igrami-gamatron', to: '/vendor/gamatron' },
	{ from: '/filter/kazino-s-igrami-fugaso', to: '/vendor/fugaso' },
	{ from: '/filter/kazino-s-igrami-fuga-gaming', to: '/vendor/fuga-gaming' },
	{ from: '/filter/kazino-s-igrami-foxium', to: '/vendor/foxium' },
	{ from: '/filter/kazino-s-igrami-felt-gaming', to: '/vendor/felt-gaming' },
	{ from: '/filter/kazino-s-igrami-felix-gaming', to: '/vendor/felix-gaming' },
	{ from: '/filter/kazino-s-igrami-fazi', to: '/vendor/fazi' },
	{
		from: '/filter/kazino-s-igrami-fantasma-games',
		to: '/vendor/fantasma-games'
	},
	{ from: '/filter/kazino-s-igrami-ezugi', to: '/vendor/ezugi' },
	{
		from: '/filter/kazino-s-igrami-evolution-gaming',
		to: '/vendor/evolution-gaming'
	},
	{
		from: '/filter/kazino-s-igrami-espresso-games',
		to: '/vendor/espresso-games'
	},
	{ from: '/filter/kazino-s-igrami-ensis', to: '/vendor/ensis' },
	{ from: '/filter/kazino-s-igrami-endorphina', to: '/vendor/endorphina' },
	{ from: '/filter/kazino-s-igrami-endemol', to: '/vendor/endemol-games' },
	{ from: '/filter/kazino-s-igrami-elk', to: '/vendor/elk-studios' },
	{ from: '/filter/kazino-s-igrami-dwg', to: '/vendor/dwg' },
	{ from: '/filter/kazino-s-igrami-dragoon-soft', to: '/vendor/dragoon-soft' },
	{ from: '/filter/kazino-s-igrami-dragonfish', to: '/vendor/dragonfish' },
	{ from: '/filter/kazino-s-igrami-ct-gaming', to: '/vendor/ct-gaming' },
	{ from: '/filter/kazino-s-igrami-cryptologic', to: '/vendor/cryptologic' },
	{ from: '/filter/kazino-s-igrami-core-gaming', to: '/vendor/core-gaming' },
	{
		from: '/filter/kazino-s-igrami-concept-gaming',
		to: '/vendor/concept-gaming'
	},
	{ from: '/filter/kazino-s-igrami-chartwell', to: '/vendor/chartwell' },
	{
		from: '/filter/kazino-s-igrami-cayetano-gaming',
		to: '/vendor/cayetano-gaming'
	},
	{
		from: '/filter/kazino-s-igrami-casino-technology',
		to: '/vendor/casino-technology'
	},
	{ from: '/filter/kazino-s-igrami-bwin-party', to: '/vendor/bwinparty' },
	{ from: '/filter/kazino-s-igrami-bunfox', to: '/vendor/bunfox' },
	{ from: '/filter/kazino-s-igrami-booongo', to: '/vendor/booongo' },
	{
		from: '/filter/kazino-s-igrami-booming-games',
		to: '/vendor/booming-games'
	},
	{
		from: '/filter/kazino-s-igrami-blueprint-gaming',
		to: '/vendor/blueprint-gaming'
	},
	{
		from: '/filter/kazino-s-igrami-bla-bla-bla-studios',
		to: '/vendor/bla-bla-bla-studios'
	},
	{
		from: '/filter/kazino-s-igrami-big-time-gamin',
		to: '/vendor/big-time-gaming'
	},
	{ from: '/filter/kazino-s-igrami-bgaming', to: '/vendor/bgaming' },
	{ from: '/filter/kazino-s-igrami-bf-games', to: '/vendor/bf-games' },
	{ from: '/filter/kazino-s-igrami-betsoft', to: '/vendor/betsoft' },
	{ from: '/filter/kazino-s-igrami-betixon', to: '/vendor/betixon' },
	{ from: '/filter/kazino-s-igrami-betgames', to: '/vendor/betgames' },
	{ from: '/filter/kazino-s-igrami-betdigital', to: '/vendor/betdigital' },
	{ from: '/filter/kazino-s-igrami-betconstruct', to: '/vendor/betconstruct' },
	{ from: '/filter/kazino-s-igrami-bbin', to: '/vendor/bbin' },
	{ from: '/filter/kazino-s-igrami-barcrest', to: '/vendor/barcrest-games' },
	{
		from: '/filter/kazino-s-igrami-bang-bang-games',
		to: '/vendor/bang-bang-games'
	},
	{
		from: '/filter/kazino-s-igrami-bally-technologies',
		to: '/vendor/bally-technologies'
	},
	{
		from: '/filter/kazino-s-igrami-authentic-gaming',
		to: '/vendor/authentic-gaming'
	},
	{ from: '/filter/kazino-s-igrami-august', to: '/vendor/august' },
	{ from: '/filter/kazino-s-igrami-atmosfera', to: '/vendor/atmosfera' },
	{ from: '/filter/kazino-s-igrami-ash-gaming', to: '/vendor/ash-gaming' },
	{ from: '/filter/kazino-s-igrami-aristocrat', to: '/vendor/aristocrat' },
	{ from: '/filter/kazino-s-igrami-apollo', to: '/vendor/apollo-games' },
	{ from: '/filter/kazino-s-igrami-amaya', to: '/vendor/amaya' },
	{ from: '/filter/kazino-s-igrami-amatic', to: '/vendor/amatic-industries' },
	{ from: '/filter/kazino-s-igrami-allwayspin', to: '/vendor/allwayspin' },
	{ from: '/filter/kazino-s-igrami-alfaplay', to: '/vendor/alfaplay' },
	{ from: '/filter/kazino-s-igrami-ainsworth', to: '/vendor/ainsworth' },
	{ from: '/filter/kazino-s-igrami-abzorba', to: '/vendor/abzorba-games' },
	{ from: '/filter/kazino-s-igrami-absolut', to: '/vendor/absolute' },
	{ from: '/filter/kazino-s-igrami-888', to: '/vendor/888' },
	{ from: '/filter/kazino-s-igrami-7-mojos', to: '/vendor/7-mojos' },
	{
		from: '/filter/kazino-s-igrami-2-by-2-gaming',
		to: '/vendor/2-by-2-gaming'
	},
	{
		from: '/filter/kazino-na-windows-mobile',
		to: '/technology/windows-mobile'
	},
	{ from: '/filter/kazino-na-pk', to: '/technology/pc' },
	{ from: '/filter/kazino-na-ios', to: '/technology/ios' },
	{ from: '/filter/kazino-na-html5', to: '/technology/html5' },
	{ from: '/filter/kazino-na-flash', to: '/technology/flash' },
	{ from: '/filter/kazino-na-android', to: '/technology/android' },
	{ from: '/filter/kazing-s-igrami-aspect-games', to: '/vendor/aspect-games' },
	{ from: '/filter/casino-s-qiwi', to: '/payment/qiwi' },
	{ from: '/filter/bonusy-pin-up-casino', to: '/casino/pin-up-casino' },
	{ from: '/filter/bonusy-kazino-william-hill', to: '/casino/william-hill' },
	{
		from: '/filter/bonusy-kazino-vulkan-original',
		to: '/casino/casino-vulkan-original'
	},
	{ from: '/filter/bonusy-kazino-vip-net-game', to: '/casino/netgame' },
	{ from: '/filter/bonusy-kazino-vegas-red', to: '/casino/vegas-red' },
	{ from: '/filter/bonusy-kazino-unibet', to: '/casino/unibet' },
	{ from: '/filter/bonusy-kazino-tropez', to: '/casino/tropez' },
	{ from: '/filter/bonusy-kazino-titan', to: '/casino/titan' },
	{ from: '/filter/bonusy-kazino-spin-palace', to: '/casino/spin-palace' },
	{ from: '/filter/bonusy-kazino-slotty-vegas', to: '/casino/slotty-vegas' },
	{ from: '/filter/bonusy-kazino-slots-magic', to: '/casino/slots-magic' },
	{ from: '/filter/bonusy-kazino-slotoking', to: '/casino/slotoking' },
	{ from: '/filter/bonusy-kazino-slotobit', to: '/casino/slotobit' },
	{ from: '/filter/bonusy-kazino-skykings', to: '/casino/skyking' },
	{ from: '/filter/bonusy-kazino-scratch-mania', to: '/casino/scratch-mania' },
	{ from: '/filter/bonusy-kazino-reel-emperor', to: '/casino/reel-emperor' },
	{ from: '/filter/bonusy-kazino-red-slots', to: '/casino/casino-red-slots' },
	{
		from: '/filter/bonusy-kazino-quasar-gaming',
		to: '/casino/casino-quasar-gaming'
	},
	{ from: '/filter/bonusy-kazino-prestige', to: '/casino/prestige' },
	{ from: '/filter/bonusy-kazino-party-casino', to: '/casino/casino-party' },
	{ from: '/filter/bonusy-kazino-paddy-power', to: '/casino/paddy-power' },
	{ from: '/filter/bonusy-kazino-osiris-casino', to: '/casino/casino-osiris' },
	{ from: '/filter/bonusy-kazino-olymp', to: '/casino/olymp' },
	{ from: '/filter/bonusy-kazino-next-casino', to: '/casino/next' },
	{ from: '/filter/bonusy-kazino-netbet', to: '/casino/netbet' },
	{ from: '/filter/bonusy-kazino-my-bet', to: '/casino/my-bet' },
	{ from: '/filter/bonusy-kazino-maria', to: '/casino/maria' },
	{
		from: '/filter/bonusy-kazino-manhattan-slots',
		to: '/casino/casino-manhattan-slots'
	},
	{ from: '/filter/bonusy-kazino-luckyred-casino', to: '/casino/lucky-red' },
	{ from: '/filter/bonusy-kazino-kazino-europaplay', to: '/casino/europaplay' },
	{ from: '/filter/bonusy-kazino-joyland', to: '/casino/joyland' },
	{ from: '/filter/bonusy-kazino-high-noon', to: '/casino/high-noon' },
	{ from: '/filter/bonusy-kazino-gratorama', to: '/casino/gratorama' },
	{ from: '/filter/bonusy-kazino-europa', to: '/casino/casino-europa' },
	{ from: '/filter/bonusy-kazino-euromoon-casino', to: '/casino/euromoon' },
	{ from: '/filter/bonusy-kazino-eurogrand', to: '/casino/eurogrand' },
	{ from: '/filter/bonusy-kazino-eucasino', to: '/casino/eucasino' },
	{ from: '/filter/bonusy-kazino-energy', to: '/casino/energy' },
	{ from: '/filter/bonusy-kazino-cruise', to: '/casino/cruise' },
	{ from: '/filter/bonusy-kazino-columbus', to: '/casino/columbus' },
	{ from: '/filter/bonusy-kazino-club-world-casino', to: '/casino/club-world' },
	{ from: '/filter/bonusy-kazino-club-vulkan', to: '/casino/vulkan-klub' },
	{ from: '/filter/bonusy-kazino-casinosjov-dk', to: '/casino/casinosjovdk' },
	{ from: '/filter/bonusy-kazino-casino-fantasia', to: '/casino/fantasia' },
	{ from: '/filter/bonusy-kazino-bellini', to: '/casino/bellini' },
	{
		from: '/filter/bonusy-kazino-atlantic-casino-club',
		to: '/casino/atlantic-club'
	},
	{
		from: '/filter/bonusy-kazino-all-star-slots',
		to: '/casino/casino-all-star-slots'
	},
	{ from: '/filter/bonusy-kazino-888', to: '/casino/casino-888' },
	{ from: '/filter/bonusy-kazino-24hbet', to: '/casino/24hbet' },
	{ from: '/filter/bonusy-kazino-21-nova', to: '/casino/21-nova' },
	{ from: '/filter/bonusy-kazino-10bet', to: '/casino/10bet' },
	{ from: '/filter/bonusy-casino-luck', to: '/casino/kazino-casino-luck' },
	{ from: '/filter/bonusy-bitcoinplay-casino', to: '/casino/bitcoinplay' },
	{ from: '/filter/1x2-gaming-casino', to: '/vendor/1x2-gaming' },
	{ from: '/casino/casino-vip-net-game', to: '/casino/netgame' },
	{ from: '/casino/kazino-netgame', to: '/casino/netgame' },
	{ from: '/casino/casino-slotoking', to: '/casino/slotoking' },
	{ from: '/casino/casino-scratch-mania', to: '/casino/scratch-mania' },
	{ from: '/casino/casino-redkings', to: '/casino/redkings' },
	{ from: '/casino/casino-next', to: '/casino/next' },
	{ from: '/casino/casino-my-bet', to: '/casino/my-bet' },
	{ from: '/casino/casino-maximum', to: '/casino/maximum' },
	{ from: '/casino/casino-lucky-red-casino', to: '/casino/lucky-red-casino' },
	{ from: '/casino/casino-luck', to: '/casino/kazino-casino-luck' },
	{ from: '/casino/casino-jackpot-city', to: '/casino/jackpot-city' },
	{ from: '/casino/casino-eurogrand', to: '/casino/eurogrand' },
	{ from: '/casino/casino-eucasino', to: '/casino/eucasino' },
	{ from: '/casino/casino-energy', to: '/casino/energy' },
	{ from: '/casino/casino-atlantic-club', to: '/casino/atlantic-club' },
	{ from: '/casino/casino-21-nova', to: '/casino/21-nova' },
	{ from: '/casino/bons-casino', to: '/casino/bons' },
	{
		from: '/bonuses-tax/vip-predlozheniya',
		to: '/type-bonus/vip-predlozheniya'
	},
	{ from: '/bonuses-tax/reload', to: '/type-bonus/reload' },
	{
		from: '/bonuses-tax/privetstvennyy-bonus',
		to: '/type-bonus/privetstvennyy-bonus'
	},
	{ from: '/bonuses-tax/paket-bonusov', to: '/type-bonus/paket-bonusov' },
	{ from: '/bonuses-tax/frispiny', to: '/type-bonus/frispiny' },
	{ from: '/bonuses-tax/drugie', to: '/type-bonus/drugie' },
	{ from: '/bonuses-tax/depozitnyy-bonus', to: '/type-bonus/depozitnyy-bonus' },
	{ from: '/bonuses-tax/cashback', to: '/type-bonus/cashback' },
	{
		from: '/bonuses-tax/bonus-na-vtoroy-depozit',
		to: '/type-bonus/bonus-na-vtoroy-depozit'
	},
	{
		from: '/bonuses-tax/bezdepozitnyy-bonus',
		to: '/type-bonus/bezdepozitnyy-bonus'
	},
	{ from: '/?post_type=game&p=88780', to: '/' },
	{ from: '/?post_type=game&p=88290', to: '/' },
	{ from: '/?post_type=game&p=87951', to: '/' },
	{ from: '/?post_type=game&p=87889', to: '/' },
	{ from: '/?post_type=game&p=71177', to: '/' },
	{
		from: '/game/igrovoj-avtomat-aztec-gold-casino-technology',
		to: '/game/aztec-gold'
	},
	{ from: '/game/igrovoj-avtomat-always-hot', to: '/game/always-hot' },
	{
		from: '/game/igrovoj-avtomat-bananas-go-bahamas',
		to: '/game/bananas-go-bahamas'
	},
	{
		from: '/game/igrovoj-avtomat-champagne-casino-technology',
		to: '/game/champagne'
	},
	{ from: '/game/igrovoj-avtomat-columbus-novomatic', to: '/game/columbus' },
	{ from: '/game/igrovoj-avtomat-crazy-monkey', to: '/game/crazy-monkey' },
	{ from: '/game/igrovoj-avtomat-dolphins-pearl', to: '/game/dolphins-pearl' },
	{ from: '/game/igrovoj-avtomat-fruit-cocktail', to: '/game/fruit-cocktail' },
	{ from: '/game/igrovoj-avtomat-garage', to: '/game/garage' },
	{ from: '/game/igrovoj-avtomat-keks', to: '/game/keks' },
	{ from: '/game/igrovoj-avtomat-lucky-haunter', to: '/game/lucky-haunter' },
	{
		from: '/game/igrovoj-avtomat-lucky-ladys-charm',
		to: '/game/lucky-ladys-charm'
	},
	{ from: '/game/igrovoj-avtomat-resident', to: '/game/resident' },
	{ from: '/game/igrovoj-avtomat-rock-climber', to: '/game/rock-climber' },
	{ from: '/game/igrovoj-avtomat-sharky', to: '/game/sharky' },
	{ from: '/game/igrovoj-avtomat-sizzling-hot', to: '/game/sizzling-hot' },
	{
		from: '/game/igrovoj-avtomat-slot-o-pol-casino-technology',
		to: '/game/slot-o-pol'
	},
	{ from: '/game/igrovoj-avtomat-the-money-game', to: '/game/the-money-game' }
]
